package com.chinasofti.pojo;

import java.io.Serializable;
import java.util.Date;

public class AjiaCartItem implements Serializable {
	
	private AjiaItem ajiaiteam;
	
    public AjiaCartItem() {
		super();
		// TODO Auto-generated constructor stub
	}

	public AjiaCartItem(AjiaItem ajiaiteam, Long id, Long userId, Long itemId, Integer num, Integer status,
			Date created, Date updated) {
		super();
		this.ajiaiteam = ajiaiteam;
		this.id = id;
		this.userId = userId;
		this.itemId = itemId;
		this.num = num;
		this.status = status;
		this.created = created;
		this.updated = updated;
	}

	public AjiaItem getAjiaiteam() {
		return ajiaiteam;
	}

	public void setAjiaiteam(AjiaItem ajiaiteam) {
		this.ajiaiteam = ajiaiteam;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_cart_item.id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_cart_item.user_id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_cart_item.item_id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_cart_item.num
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_cart_item.status
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_cart_item.created
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_cart_item.updated
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_cart_item.id
     *
     * @return the value of ajia_cart_item.id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_cart_item.id
     *
     * @param id the value for ajia_cart_item.id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_cart_item.user_id
     *
     * @return the value of ajia_cart_item.user_id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_cart_item.user_id
     *
     * @param userId the value for ajia_cart_item.user_id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_cart_item.item_id
     *
     * @return the value of ajia_cart_item.item_id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_cart_item.item_id
     *
     * @param itemId the value for ajia_cart_item.item_id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_cart_item.num
     *
     * @return the value of ajia_cart_item.num
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_cart_item.num
     *
     * @param num the value for ajia_cart_item.num
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_cart_item.status
     *
     * @return the value of ajia_cart_item.status
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_cart_item.status
     *
     * @param status the value for ajia_cart_item.status
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_cart_item.created
     *
     * @return the value of ajia_cart_item.created
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_cart_item.created
     *
     * @param created the value for ajia_cart_item.created
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_cart_item.updated
     *
     * @return the value of ajia_cart_item.updated
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_cart_item.updated
     *
     * @param updated the value for ajia_cart_item.updated
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    @Override
	public String toString() {
		return "AjiaCartItem [ajiaiteam=" + ajiaiteam + ", id=" + id + ", userId=" + userId + ", itemId=" + itemId
				+ ", num=" + num + ", status=" + status + ", created=" + created + ", updated=" + updated + "]";
	}
}