package com.chinasofti.pojo;

import java.io.Serializable;
import java.util.Date;

public class AjiaContent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.category_id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.title
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.sub_title
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.title_desc
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private String titleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.url
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.pic
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.pic2
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private String pic2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.created
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.updated
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ajia_content.content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.id
     *
     * @return the value of ajia_content.id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.id
     *
     * @param id the value for ajia_content.id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.category_id
     *
     * @return the value of ajia_content.category_id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.category_id
     *
     * @param categoryId the value for ajia_content.category_id
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.title
     *
     * @return the value of ajia_content.title
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.title
     *
     * @param title the value for ajia_content.title
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.sub_title
     *
     * @return the value of ajia_content.sub_title
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.sub_title
     *
     * @param subTitle the value for ajia_content.sub_title
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.title_desc
     *
     * @return the value of ajia_content.title_desc
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public String getTitleDesc() {
        return titleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.title_desc
     *
     * @param titleDesc the value for ajia_content.title_desc
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setTitleDesc(String titleDesc) {
        this.titleDesc = titleDesc == null ? null : titleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.url
     *
     * @return the value of ajia_content.url
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.url
     *
     * @param url the value for ajia_content.url
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.pic
     *
     * @return the value of ajia_content.pic
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.pic
     *
     * @param pic the value for ajia_content.pic
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.pic2
     *
     * @return the value of ajia_content.pic2
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public String getPic2() {
        return pic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.pic2
     *
     * @param pic2 the value for ajia_content.pic2
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setPic2(String pic2) {
        this.pic2 = pic2 == null ? null : pic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.created
     *
     * @return the value of ajia_content.created
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.created
     *
     * @param created the value for ajia_content.created
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.updated
     *
     * @return the value of ajia_content.updated
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.updated
     *
     * @param updated the value for ajia_content.updated
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ajia_content.content
     *
     * @return the value of ajia_content.content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ajia_content.content
     *
     * @param content the value for ajia_content.content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", title=").append(title);
        sb.append(", subTitle=").append(subTitle);
        sb.append(", titleDesc=").append(titleDesc);
        sb.append(", url=").append(url);
        sb.append(", pic=").append(pic);
        sb.append(", pic2=").append(pic2);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}