package com.chinasofti.mapper;

import com.chinasofti.pojo.AjiaItemParam;
import com.chinasofti.pojo.AjiaItemParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaItemParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    long countByExample(AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByExample(AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insert(AjiaItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insertSelective(AjiaItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    List<AjiaItemParam> selectByExampleWithBLOBs(AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    List<AjiaItemParam> selectByExample(AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    AjiaItemParam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") AjiaItemParam record, @Param("example") AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") AjiaItemParam record, @Param("example") AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExample(@Param("record") AjiaItemParam record, @Param("example") AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKeySelective(AjiaItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(AjiaItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKey(AjiaItemParam record);
}