package com.chinasofti.mapper;

import com.chinasofti.pojo.AjiaContent;
import com.chinasofti.pojo.AjiaContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    long countByExample(AjiaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByExample(AjiaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insert(AjiaContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insertSelective(AjiaContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    List<AjiaContent> selectByExampleWithBLOBs(AjiaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    List<AjiaContent> selectByExample(AjiaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    AjiaContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") AjiaContent record, @Param("example") AjiaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") AjiaContent record, @Param("example") AjiaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExample(@Param("record") AjiaContent record, @Param("example") AjiaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKeySelective(AjiaContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(AjiaContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKey(AjiaContent record);
}