package com.chinasofti.mapper;

import com.chinasofti.pojo.AjiaItemParamItem;
import com.chinasofti.pojo.AjiaItemParamItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaItemParamItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    long countByExample(AjiaItemParamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByExample(AjiaItemParamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insert(AjiaItemParamItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insertSelective(AjiaItemParamItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    List<AjiaItemParamItem> selectByExampleWithBLOBs(AjiaItemParamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    List<AjiaItemParamItem> selectByExample(AjiaItemParamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    AjiaItemParamItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") AjiaItemParamItem record, @Param("example") AjiaItemParamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") AjiaItemParamItem record, @Param("example") AjiaItemParamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExample(@Param("record") AjiaItemParamItem record, @Param("example") AjiaItemParamItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKeySelective(AjiaItemParamItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(AjiaItemParamItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKey(AjiaItemParamItem record);
}