package com.chinasofti.mapper;

import com.chinasofti.pojo.AjiaCollectItem;
import com.chinasofti.pojo.AjiaCollectItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaCollectItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    long countByExample(AjiaCollectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByExample(AjiaCollectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insert(AjiaCollectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insertSelective(AjiaCollectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    List<AjiaCollectItem> selectByExample(AjiaCollectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    AjiaCollectItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") AjiaCollectItem record, @Param("example") AjiaCollectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExample(@Param("record") AjiaCollectItem record, @Param("example") AjiaCollectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKeySelective(AjiaCollectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_collect_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKey(AjiaCollectItem record);
}