package com.chinasofti.mapper;

import com.chinasofti.pojo.AjiaContentCategory;
import com.chinasofti.pojo.AjiaContentCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaContentCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    long countByExample(AjiaContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByExample(AjiaContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insert(AjiaContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insertSelective(AjiaContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    List<AjiaContentCategory> selectByExample(AjiaContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    AjiaContentCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") AjiaContentCategory record, @Param("example") AjiaContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExample(@Param("record") AjiaContentCategory record, @Param("example") AjiaContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKeySelective(AjiaContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_content_category
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKey(AjiaContentCategory record);
}