package com.chinasofti.mapper;

import com.chinasofti.pojo.AjiaCartItem;
import com.chinasofti.pojo.AjiaCartItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaCartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    long countByExample(AjiaCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByExample(AjiaCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insert(AjiaCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int insertSelective(AjiaCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    List<AjiaCartItem> selectByExample(AjiaCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    AjiaCartItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") AjiaCartItem record, @Param("example") AjiaCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByExample(@Param("record") AjiaCartItem record, @Param("example") AjiaCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKeySelective(AjiaCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_cart_item
     *
     * @mbg.generated Wed Sep 11 17:20:26 CST 2019
     */
    int updateByPrimaryKey(AjiaCartItem record);
}